<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Here we provide a detailed analysis using more sophisticated statistics techniques.">

<title>MA [46]15 Final Project: Group 10 - Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MA [46]15 Final Project: Group 10</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">MA [46]15 Final Project: Group 10</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./big_picture.html"> 
<span class="menu-text">Locked Down by COVID-19: The Racial Reality of California’s Prisons</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./analysis.html" aria-current="page"> 
<span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data.html"> 
<span class="menu-text">Data</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#total-prison-admissions-and-releases" id="toc-total-prison-admissions-and-releases" class="nav-link" data-scroll-target="#total-prison-admissions-and-releases">Total Prison Admissions and Releases</a></li>
  <li><a href="#admissions-and-releases-by-race" id="toc-admissions-and-releases-by-race" class="nav-link" data-scroll-target="#admissions-and-releases-by-race">Admissions and Releases by Race</a>
  <ul class="collapse">
  <li><a href="#total-white-admissions-and-releases" id="toc-total-white-admissions-and-releases" class="nav-link" data-scroll-target="#total-white-admissions-and-releases">Total White Admissions and Releases</a></li>
  <li><a href="#total-black-admissions-and-releases" id="toc-total-black-admissions-and-releases" class="nav-link" data-scroll-target="#total-black-admissions-and-releases">Total Black Admissions and Releases</a></li>
  <li><a href="#total-hispanic-admissions-and-releases" id="toc-total-hispanic-admissions-and-releases" class="nav-link" data-scroll-target="#total-hispanic-admissions-and-releases">Total Hispanic Admissions and Releases</a></li>
  </ul></li>
  <li><a href="#modeling-and-inference" id="toc-modeling-and-inference" class="nav-link" data-scroll-target="#modeling-and-inference">Modeling and Inference</a>
  <ul class="collapse">
  <li><a href="#model-1-admissions-vs.-total-monthly-covid-19-cases" id="toc-model-1-admissions-vs.-total-monthly-covid-19-cases" class="nav-link" data-scroll-target="#model-1-admissions-vs.-total-monthly-covid-19-cases">Model 1: Admissions vs.&nbsp;Total Monthly COVID-19 Cases</a></li>
  <li><a href="#model-2-admissions-vs.-total-monthly-covid-19-deaths" id="toc-model-2-admissions-vs.-total-monthly-covid-19-deaths" class="nav-link" data-scroll-target="#model-2-admissions-vs.-total-monthly-covid-19-deaths">Model 2: Admissions vs.&nbsp;Total Monthly COVID-19 Deaths</a></li>
  </ul></li>
  <li><a href="#california-analysis" id="toc-california-analysis" class="nav-link" data-scroll-target="#california-analysis">California Analysis</a>
  <ul class="collapse">
  <li><a href="#demographic-overview-of-california-in-2020" id="toc-demographic-overview-of-california-in-2020" class="nav-link" data-scroll-target="#demographic-overview-of-california-in-2020">Demographic Overview of California in 2020</a></li>
  <li><a href="#original-dataset-analysis" id="toc-original-dataset-analysis" class="nav-link" data-scroll-target="#original-dataset-analysis">Original Dataset Analysis</a></li>
  <li><a href="#alternative-dataset-analysis" id="toc-alternative-dataset-analysis" class="nav-link" data-scroll-target="#alternative-dataset-analysis">Alternative Dataset Analysis</a></li>
  <li><a href="#minor-monthly-variations" id="toc-minor-monthly-variations" class="nav-link" data-scroll-target="#minor-monthly-variations">2019: Minor Monthly Variations</a></li>
  <li><a href="#noticeable-differences-during-covid-19-impact" id="toc-noticeable-differences-during-covid-19-impact" class="nav-link" data-scroll-target="#noticeable-differences-during-covid-19-impact">2020: Noticeable Differences During COVID-19 Impact</a></li>
  <li><a href="#differences-in-the-path-back-to-balance" id="toc-differences-in-the-path-back-to-balance" class="nav-link" data-scroll-target="#differences-in-the-path-back-to-balance">2021: Differences in the Path Back to Balance</a></li>
  <li><a href="#summary-of-dataset-comparisons" id="toc-summary-of-dataset-comparisons" class="nav-link" data-scroll-target="#summary-of-dataset-comparisons">Summary of Dataset Comparisons</a></li>
  </ul></li>
  <li><a href="#limitations-and-future-work" id="toc-limitations-and-future-work" class="nav-link" data-scroll-target="#limitations-and-future-work">Limitations and Future Work</a>
  <ul class="collapse">
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work">Future Work</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis</h1>
</div>

<div>
  <div class="description">
    Here we provide a detailed analysis using more sophisticated statistics techniques.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="images/Analysis.jpg" class="img-fluid"></p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This analysis aims to uncover significant patterns and insights from prison admissions and releases data during the COVID-19 pandemic. We explore the relationships between admissions, releases, and COVID-19 cases and deaths, emphasizing trends across different racial groups and focusing on California as a case study due to its diversity and population size. By integrating statistical modeling, we strive to elucidate the broader impacts of the pandemic on the correctional system and highlight areas for further investigation.</p>
</section>
<section id="total-prison-admissions-and-releases" class="level1">
<h1>Total Prison Admissions and Releases</h1>
<p><img src="images/total 18 all race.png" class="img-fluid"></p>
<p>The plot titled “Total Prison Admissions and Releases for 18 States (2019-2022)” provides insights into the trends of total prison admissions and releases during this period, with the blue line representing admissions and the red line indicating releases. The data captures patterns before, during, and after the COVID-19 pandemic. Notably, there is a significant decline in admissions from February to April 2020, with counts dropping from 17500 to just below 5000, coinciding with the early rise of the pandemic. Additionally, two spikes in releases are observed: one in April 2020, possibly related to prison population management, and another in July 2020.</p>
<p>The subsequent rise in admissions during September 2020, followed by a decline until November, suggests evolving responses within the correctional system. While this analysis highlights distinct patterns, it is essential to consider potential factors behind these trends. For instance, the lockdown may have contributed to reduced crime rates due to fewer people being outside, leading to fewer arrests. Additionally, individuals with minor offenses might have been released earlier to manage the pandemic’s impact on prison populations. However, these interpretations are hypotheses that require further investigation and reading to confirm their validity.</p>
<p>This analysis underscores the complexity of interpreting shifts in prison data during unprecedented events like the COVID-19 pandemic.</p>
</section>
<section id="admissions-and-releases-by-race" class="level1">
<h1>Admissions and Releases by Race</h1>
<p>These race categories exhibit similar patterns, with a surge in releases and a decline in admissions, from March to June 2020.</p>
<section id="total-white-admissions-and-releases" class="level3">
<h3 class="anchored" data-anchor-id="total-white-admissions-and-releases">Total White Admissions and Releases</h3>
<p><img src="images/white18.png" class="img-fluid"> In the white population plot, there is a steady trend in admissions and releases. Until March 2020, there is a spike in releases while there is a decrease in admissions. Then, as the admission slowly increases and the releases decrease, there occurs a small spike and decrease again in releases and admissions. Towards November 2020 and onwards, the relationship between admissions and releases starts to regulate but not in the same numbers as in 2019.</p>
</section>
<section id="total-black-admissions-and-releases" class="level3">
<h3 class="anchored" data-anchor-id="total-black-admissions-and-releases">Total Black Admissions and Releases</h3>
<p><img src="images/Black18.png" class="img-fluid"> The graph illustrates trends in Black admissions and releases from 2019 to 2022. Both lines display relative stability in early 2019; however, admissions experience a sharp decline around March 2020, likely due to COVID-19 disruptions. Admissions decreased to around 500 by April 2020, while releases exhibit more fluctuations. Notably, there are two spikes in releases: one in April 2020, possibly related to efforts to manage prison populations during the pandemic, and another in July 2020. Admissions show some recovery, reaching around 3500 by late 2020, but remain significantly lower than pre-pandemic levels.</p>
</section>
<section id="total-hispanic-admissions-and-releases" class="level3">
<h3 class="anchored" data-anchor-id="total-hispanic-admissions-and-releases">Total Hispanic Admissions and Releases</h3>
<p><img src="images/Hispanic18.png" class="img-fluid"> The graph illustrates trends in Hispanic admissions and releases from 2019 to 2022. Prior to 2020, both admissions and releases have a relatively steady trend, with releases slightly higher than admissions at times. Around March 2020 (the start of the COVID-19 pandemic), there’s a sharp drop in admissions (from approximately 4200 to less than 1000). There are two spikes in releases shortly after, possibly as a response to the pandemic. After the initial pandemic impact, both admissions and releases fluctuate, but the admissions remain lower than pre-2020 levels. Releases eventually stabilize around mid-2021 but continue to hover close to the admission rates.</p>
</section>
</section>
<section id="modeling-and-inference" class="level1">
<h1>Modeling and Inference</h1>
<p>To further understand the relationship between COVID-19 metrics and prison admissions, we employed statistical modeling. We modeled monthly admissions as a function of total monthly COVID-19 cases and deaths.</p>
<section id="model-1-admissions-vs.-total-monthly-covid-19-cases" class="level3">
<h3 class="anchored" data-anchor-id="model-1-admissions-vs.-total-monthly-covid-19-cases">Model 1: Admissions vs.&nbsp;Total Monthly COVID-19 Cases</h3>
<pre class="plaintext"><code>Call:
lm(formula = monthly_admissions ~ total_monthly_cases, data = model_data)
 
Residuals:
   Min     1Q Median     3Q    Max 
-10963  -1328   1155   2767   3891
 
Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          1.576e+04  8.276e+02   19.04   &lt;2e-16 ***
total_monthly_cases -2.652e-03  8.261e-04   -3.21   0.0029 **
 
Residual standard error: 3927 on 34 degrees of freedom
Multiple R-squared:  0.2326, Adjusted R-squared:   0.21 
F-statistic:  10.3 on 1 and 34 DF,  p-value: 0.002897</code></pre>
<p>In this linear regression model, the intercept (15760) represents the expected number of monthly admissions when COVID-19 cases are zero. The coefficient for total monthly cases (-0.002652) indicates a slight decrease in admissions for each additional COVID-19 case, with a p-value of 0.0029, demonstrating statistical significance. The model explains 23.26% of the variation in admissions.</p>
</section>
<section id="model-2-admissions-vs.-total-monthly-covid-19-deaths" class="level3">
<h3 class="anchored" data-anchor-id="model-2-admissions-vs.-total-monthly-covid-19-deaths">Model 2: Admissions vs.&nbsp;Total Monthly COVID-19 Deaths</h3>
<pre class="plaintext"><code>Call:
lm(formula = monthly_admissions ~ total_monthly_deaths, data = model_data)
 
Residuals:
    Min      1Q  Median      3Q     Max 
-9303.1  -888.1   800.7  2391.2  3795.0
 
Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           1.648e+04  7.608e+02  21.659  &lt; 2e-16 ***
total_monthly_deaths -2.685e-01  5.645e-02  -4.756 3.55e-05 ***
 
Residual standard error: 3474 on 34 degrees of freedom
Multiple R-squared:  0.3995, Adjusted R-squared:  0.3819 
F-statistic: 22.62 on 1 and 34 DF,  p-value: 3.549e-05</code></pre>
<p>In this linear regression model, the intercept (16480) represents the expected monthly admissions when COVID-19 deaths are zero. The coefficient for total monthly deaths (-0.2685) indicates a larger decrease in admissions for each additional COVID-19 death. The p-value (&lt;0.0001) signifies high statistical significance. The model explains 39.95% of the variation in admissions, performing better than the previous model.</p>
<p>Both models demonstrate significant negative relationships between COVID-19 metrics and prison admissions, highlighting the pandemic’s potential influence on correctional system dynamics.</p>
<p>The negative coefficient for the modeling results of admissions aligns with the patterns observed in the EDA plots, where both COVID cases and deaths were associated with a decline in prison admissions over time. This consistency between the statistical findings and visual analysis reinforces the observed relationships in the data.</p>
</section>
</section>
<section id="california-analysis" class="level1">
<h1>California Analysis</h1>
<p>To deepen our insights, we narrowed our focus to California, the most populous state with significant racial diversity. This allows us to observe patterns that might not be evident in aggregate data.</p>
<section id="demographic-overview-of-california-in-2020" class="level3">
<h3 class="anchored" data-anchor-id="demographic-overview-of-california-in-2020">Demographic Overview of California in 2020</h3>
<p><img src="images/CA demo 2020.jpg" class="img-fluid"></p>
<p>Using US Census Bureau data, California’s racial demographics for 2020 revealed that Hispanic/Latino populations were the largest group, followed by White, Black, and Other categories. The population remained relatively consistent during 2019-2021, with Hispanic/Latino populations increasing slightly. These demographics provide a context for understanding disparities in prison admissions and releases.</p>
<p><img src="images/CA original.png" class="img-fluid"></p>
</section>
<section id="original-dataset-analysis" class="level3">
<h3 class="anchored" data-anchor-id="original-dataset-analysis">Original Dataset Analysis</h3>
<p>The analysis of California’s prison admissions and releases data from January 2019 to December 2021 highlights notable shifts, particularly during 2020, likely driven by the COVID-19 pandemic. In January 2019, admissions were 2716 and releases were 3476, showing a slightly higher rate of releases than admissions. This pattern persisted throughout 2019. By 2020, admissions dropped sharply while releases surged, especially in April and July, reflecting policies to reduce prison populations. By 2021, admissions gradually increased, narrowing the gap between admissions and releases.</p>
<p><img src="images/CA alternative.png" class="img-fluid"></p>
</section>
<section id="alternative-dataset-analysis" class="level3">
<h3 class="anchored" data-anchor-id="alternative-dataset-analysis">Alternative Dataset Analysis</h3>
<p>That was the analysis based on our original dataset, selected as the foundation of our study from day one. Our group has since identified a complementary California-specific dataset from the California Department of Corrections and Rehabilitation, available at https://data.ca.gov/dataset/monthly-admissions-and-releases. This new California dataset, titled “California’s Monthly Admissions and Releases,” provides monthly records of the number of individuals admitted to and released from California’s CDCR custody from January 31, 2014, to the present. The analysis of California’s prison admissions and releases from January 2019 to January 2022 reveals small discrepancies between the two datasets. Differences, particularly during the pandemic, may result from variations in data collection methods. Despite these discrepancies, both datasets align well in illustrating broader trends.</p>
</section>
<section id="minor-monthly-variations" class="level3">
<h3 class="anchored" data-anchor-id="minor-monthly-variations">2019: Minor Monthly Variations</h3>
<p>In 2019, both datasets consistently show that releases exceeded admissions, suggesting a gradual reduction in the prison population across California. However, some monthly figures vary slightly. For instance, in November 2019, the original dataset records 2592 admissions and 3050 releases, while the new dataset reports 2590 admissions and 3024 releases. Similarly, in December 2019, our original dataset shows 2705 admissions and 3260 releases, whereas the new dataset lists 2702 admissions and 3253 releases. These small differences, although unlikely to impact overall trends significantly, suggest subtle differences in reporting or rounding conventions between the two sources.</p>
</section>
<section id="noticeable-differences-during-covid-19-impact" class="level3">
<h3 class="anchored" data-anchor-id="noticeable-differences-during-covid-19-impact">2020: Noticeable Differences During COVID-19 Impact</h3>
<p>The most significant discrepancies appear during 2020, a year marked by drastic policy changes in response to COVID-19. Both datasets reflect a steep decline in admissions and a surge in releases as California likely implemented measures to reduce prison populations. However, the specifics differ. For example, in April 2020, our original dataset records 9 admissions and 4629 releases, while the new dataset shows only 2 admissions with 4627 releases.</p>
<p>A similar pattern is observed in July 2020, a peak period for releases: the original dataset lists 9 admissions and 7522 releases, whereas the new dataset shows 3 admissions and 7520 releases. Although these variations are minor, they indicate that each dataset has slightly different figures, potentially due to differences in data classification or inclusion criteria. Additionally, both datasets capture the high release counts around mid-2020, though the new dataset tends to show slightly lower total releases for certain months.</p>
</section>
<section id="differences-in-the-path-back-to-balance" class="level3">
<h3 class="anchored" data-anchor-id="differences-in-the-path-back-to-balance">2021: Differences in the Path Back to Balance</h3>
<p>In 2021, as admissions and releases began to move toward a balance, the datasets remain aligned in terms of general trends but continue to differ in specific numbers. In January 2021, for instance, our original dataset shows 593 admissions and 1820 releases, while the new dataset records 409 admissions and 1817 releases. As the year progresses, both datasets display more consistency. By July 2021, the numbers are nearly identical, with both datasets showing 2961 admissions, although our original dataset reports 2459 releases, while the new dataset lists 2457. By December 2021, the two datasets converge closely, with both listing around 2904 admissions and 2637-2640 releases, signaling a return to pre-COVID patterns.</p>
</section>
<section id="summary-of-dataset-comparisons" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-dataset-comparisons">Summary of Dataset Comparisons</h3>
<p>Overall, both datasets depict three distinct phases in California’s prison admissions and releases: a stable 2019, a drastic adjustment period in 2020 due to COVID-19, and a gradual return to balance in 2021. Minor discrepancies, particularly in 2020, suggest variations in data reporting practices between the sources, which may influence specific monthly totals. Despite these differences, the datasets align well in illustrating the broader trends, reinforcing the understanding of California’s response to the pandemic within its prison system.</p>
</section>
</section>
<section id="limitations-and-future-work" class="level1">
<h1>Limitations and Future Work</h1>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<ul>
<li><strong>Data Scope:</strong> Our models relied on aggregated state-level data, which might obscure localized trends or policies.</li>
<li><strong>Predictor Variables:</strong> The models primarily focused on COVID-19 metrics, leaving out other potential predictors such as economic indicators or policy changes.</li>
<li><strong>Data Quality:</strong> Variations between datasets highlight challenges in standardizing data collection and reporting practices.</li>
</ul>
</section>
<section id="future-work" class="level3">
<h3 class="anchored" data-anchor-id="future-work">Future Work</h3>
<ul>
<li>Integrating additional predictors, such as unemployment rates or policy interventions, could enhance model performance.</li>
<li>Exploring data at a more granular level, such as county-level analysis, might provide deeper insights.</li>
<li>Examining longer-term impacts of the pandemic on prison systems would offer a more comprehensive understanding.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sussmanbu\.github\.io\/ma-4615-fa24-final-project-group\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>