---
title: "Blog Post 3"
subtitle: "Phase 1 of the EDA"
description:  |
  Data Link:
  https://www.kaggle.com/datasets/konradb/prison-population-in-the-us?select=populations_states.csv
author: "Group 10"
date: "2024-10-23"
categories: [Blog Post 3]
date-modified: "2024-10-23"
draft: FALSE
---

We decided to do some exploratory data analysis to understand what is going on with our data.

```{r}
data = readRDS("dataset/cleaned_dataset.rds")
head(data)
```


```{r fig.width = 12, fig.height=6}
library(ggplot2)
library(dplyr)

data$date <- as.Date(data$Date)

data_grouped <- data %>%
  group_by(date) %>%
  summarise(
    admissions_total = sum(Total_Admissions, na.rm = TRUE),
    releases_total = sum(Total_Releases, na.rm = TRUE)
  )

ggplot(data_grouped, aes(x = date)) +
  geom_line(aes(y = admissions_total, color = "Total Admissions"), linewidth = 1) +
  geom_line(aes(y = releases_total, color = "Total Releases"), linewidth = 1) +
  geom_point(aes(y = admissions_total, color = "Total Admissions"), size = 2) +
  geom_point(aes(y = releases_total, color = "Total Releases"), size = 2) +
  ggtitle("Time Series of Total Prison Admissions and Releases Over Time") +
  xlab("Date") +
  ylab("Count") +
  scale_color_manual(values = c("Total Admissions" = "blue", "Total Releases" = "red")) +
  theme_minimal() +
  theme(
    legend.title = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )

```

