{
  "hash": "9bff84ac4413184d12e06df287208687",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Blog Post 4\"\nsubtitle: \"Phase 2 of the EDA\"\ndescription:  |\n  Data Link:\n  https://www.kaggle.com/datasets/konradb/prison-population-in-the-us?select=populations_states.csv\nauthor: \"Group 10\"\ndate: \"2024-11-1\"\ncategories: [Blog Post 4]\ndate-modified: \"2024-11-1\"\ndraft: FALSE\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stats)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\ndata <- readRDS(\"dataset/cleaned_dataset.rds\")\n\ndata <- data %>% \n  mutate(Date = as.Date(Date, format = \"%Y-%m-%d\")) %>%\n  filter(Date >= as.Date(\"2019-01-01\") & Date <= as.Date(\"2022-12-31\"))\n\ndata$State <- as.factor(data$State)\n\nmodel_admissions <- lm(Total_Admissions ~ State + White_Admissions + Black_Admissions + Hispanic_Admissions + AmericanIndian_Admissions + Asian_Admissions + Other_Admissions, data = data)\n\nsummary(model_admissions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Total_Admissions ~ State + White_Admissions + Black_Admissions + \n    Hispanic_Admissions + AmericanIndian_Admissions + Asian_Admissions + \n    Other_Admissions, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-593.04   -4.26    0.21    4.96   99.03 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                16.64448   16.02746   1.038 0.299371    \nStateCalifornia            -5.30528   18.42435  -0.288 0.773464    \nStateColorado              -5.91214   13.89351  -0.426 0.670570    \nStateIdaho                 33.65929   15.13831   2.223 0.026481 *  \nStateIllinois             -28.12008   20.89911  -1.346 0.178863    \nStateIowa                  -2.60344   16.25721  -0.160 0.872813    \nStateKansas                 3.70535   15.76012   0.235 0.814188    \nStateKentucky              85.76919   23.01417   3.727 0.000208 ***\nStateMaine                -10.04699   16.61037  -0.605 0.545452    \nStateMassachusetts          9.09753   17.61178   0.517 0.605615    \nStateMontana              -10.91037   13.45918  -0.811 0.417836    \nStateNebraska               6.07975   17.15460   0.354 0.723131    \nStateOregon                 4.99220   16.12922   0.310 0.757017    \nStateTexas                  1.34177   21.36082   0.063 0.949931    \nStateUtah                  -5.72232   15.38969  -0.372 0.710125    \nStateWashington           -10.16531   16.33754  -0.622 0.533995    \nStateWest Virginia          4.02838   17.32348   0.233 0.816183    \nStateWisconsin             -8.54323   13.76453  -0.621 0.535004    \nWhite_Admissions            0.89458    0.01554  57.549  < 2e-16 ***\nBlack_Admissions            1.09024    0.02676  40.734  < 2e-16 ***\nHispanic_Admissions         1.05414    0.02040  51.676  < 2e-16 ***\nAmericanIndian_Admissions   1.01937    0.17077   5.969 3.67e-09 ***\nAsian_Admissions            1.81230    0.59280   3.057 0.002313 ** \nOther_Admissions            0.43099    0.13474   3.199 0.001438 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 34.73 on 754 degrees of freedom\nMultiple R-squared:  0.9989,\tAdjusted R-squared:  0.9988 \nF-statistic: 2.905e+04 on 23 and 754 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_releases <- lm(Total_Releases ~ State + White_Releases + Black_Releases + Hispanic_Releases + AmericanIndian_Releases + Asian_Releases + Other_Releases, data = data)\n\nsummary(model_releases)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Total_Releases ~ State + White_Releases + Black_Releases + \n    Hispanic_Releases + AmericanIndian_Releases + Asian_Releases + \n    Other_Releases, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-38.362  -2.614  -0.195   2.500  81.689 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             -10.850271   5.309833  -2.043 0.041357 *  \nStateCalifornia          46.308345   5.821646   7.955 6.58e-15 ***\nStateColorado            -4.182220   4.317501  -0.969 0.333022    \nStateIdaho               22.063175   4.691957   4.702 3.06e-06 ***\nStateIllinois            33.194702   7.493596   4.430 1.08e-05 ***\nStateIowa                13.643351   5.288195   2.580 0.010069 *  \nStateKansas              18.209732   5.147740   3.537 0.000429 ***\nStateKentucky            32.016558   6.755024   4.740 2.56e-06 ***\nStateMaine               15.052525   5.362681   2.807 0.005131 ** \nStateMassachusetts       27.340361   5.567624   4.911 1.11e-06 ***\nStateMontana             14.804851   4.396600   3.367 0.000797 ***\nStateNebraska            25.448722   5.544387   4.590 5.19e-06 ***\nStateOregon              10.172038   5.111701   1.990 0.046957 *  \nStateTexas              -89.194401   7.083296 -12.592  < 2e-16 ***\nStateUtah                13.202530   4.820991   2.739 0.006317 ** \nStateWashington          13.800352   5.075242   2.719 0.006695 ** \nStateWest Virginia       14.184004   5.602267   2.532 0.011549 *  \nStateWisconsin           30.608638   4.655488   6.575 9.10e-11 ***\nWhite_Releases            1.002474   0.003693 271.452  < 2e-16 ***\nBlack_Releases            0.949389   0.008091 117.338  < 2e-16 ***\nHispanic_Releases         1.122526   0.004644 241.696  < 2e-16 ***\nAmericanIndian_Releases   0.843773   0.049588  17.016  < 2e-16 ***\nAsian_Releases            0.932163   0.138979   6.707 3.89e-11 ***\nOther_Releases            0.022645   0.004765   4.752 2.41e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.207 on 754 degrees of freedom\nMultiple R-squared:  0.9999,\tAdjusted R-squared:  0.9999 \nF-statistic: 6.487e+05 on 23 and 754 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nThis analysis highlights how both state and racial factors influence prison admissions and releases from 2019 to 2022.\n\nAdmissions Model:\n\nWith an R² of 0.9989, the admissions model shows that state and race-specific admissions strongly impact total admissions. Significant coefficients for racial groups, such as White_Admissions and Black_Admissions, reveal how increases in admissions among these groups substantially affect overall numbers, reflecting potential disparities in incarceration.\nSome states, like Kentucky and Idaho, show unique impacts on admission rates, likely due to state-specific policies or demographic factors.\nReleases Model:\n\nThe releases model, with an R² of 0.9999, effectively captures variations in releases across racial groups and states. High coefficients for racial groups suggest that releases in each group proportionally influence total releases, hinting at systemic differences in how groups are processed for release.\nCertain states, such as California and Texas, exhibit distinctive release patterns. For instance, California’s positive coefficient may reflect state efforts to manage prison populations, while Texas’s negative coefficient suggests lower release rates, possibly tied to local policies.\nInterpretation and Implications:\n\nBoth State and Race factors underscore geographic and racial disparities in incarceration practices. States with lower-than-expected release rates could benefit from policy adjustments for equitable practices, while the racial disparities observed in admissions suggest areas for justice reform.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}